// List of proper names of stars
// https://en.wikipedia.org/wiki/List_of_proper_names_of_stars
//
// On that page, open the developer console, then this bit of jquery will get you close:
//   $('tr td:nth-child(3)').each(function() { console.log($(this).text()) })
const stars = [
  "Absolutno",
  "Acamar",
  "Achernar",
  "Achird",
  "Acrab",
  "Acrux",
  "Acubens",
  "Adhafera",
  "Adhara",
  "Adhil",
  "Ain",
  "Ainalrami",
  "Aiolos",
  "Aladfar",
  "Alasia",
  "Alathfar",
  "Albaldah",
  "Albali",
  "Albireo",
  "Alchiba",
  "Alcor",
  "Alcyone",
  "Aldebaran",
  "Alderamin",
  "Aldhanab",
  "Aldhibah",
  "Aldulfin",
  "Alfirk",
  "Algedi",
  "Algenib",
  "Algieba",
  "Algol",
  "Algorab",
  "Alhena",
  "Alioth",
  "Aljanah",
  "Alkaid",
  "Alkalurops",
  "Alkaphrah",
  "Alkarab",
  "Alkes",
  "Almaaz",
  "Almach",
  "Al Minliar al Asad",
  "Alnair",
  "Alnasl",
  "Alnilam",
  "Alnitak",
  "Alniyat",
  "Alphard",
  "Alphecca",
  "Alpheratz",
  "Alpherg",
  "Alrakis",
  "Alrescha",
  "Alruba",
  "Alsafi",
  "Alsciaukat",
  "Alsephina",
  "Alshain",
  "Alshat",
  "Altair",
  "Altais",
  "Alterf",
  "Aludra",
  "Alula Australis",
  "Alula Borealis",
  "Alya",
  "Alzirr",
  "Amadioha",
  "Amansinaya",
  "Anadolu",
  "Añañuca",
  "Ancha",
  "Angetenar",
  "Aniara",
  "Ankaa",
  "Anser",
  "Antares",
  "Arcalís",
  "Arcturus",
  "Arkab Posterior",
  "Arkab Prior",
  "Arneb",
  "Ascella",
  "Asellus Australis",
  "Asellus Borealis",
  "Ashlesha",
  "Asellus Primus",
  "Asellus Secundus",
  "Asellus Tertius",
  "Aspidiske",
  "Asterope",
  "Atakoraka",
  "Athebyne",
  "Atik",
  "Atlas",
  "Atria",
  "Avior",
  "Axólotl",
  "Ayeyarwady",
  "Azelfafage",
  "Azha",
  "Azmidi",
  "Baekdu",
  "Barnard's Star",
  "Baten Kaitos",
  "Batsũ̀",
  "Beemim",
  "Beid",
  "Belel",
  "Bélénos",
  "Bellatrix",
  "Berehynia",
  "Betelgeuse",
  "Bharani",
  "Bibhā",
  "Biham",
  "Bosona",
  "Botein",
  "Brachium",
  "Bubup",
  "Buna",
  "Bunda",
  "Canopus",
  "Capella",
  "Caph",
  "Castor",
  "Castula",
  "Cebalrai",
  "Ceibo",
  "Celaeno",
  "Cervantes",
  "Chalawan",
  "Chamukuy",
  "Chaophraya",
  "Chara",
  "Chasoň",
  "Chechia",
  "Chertan",
  "Citadelle",
  "Citalá",
  "Cocibolca",
  "Copernicus",
  "Cor Caroli",
  "Cujam",
  "Cursa",
  "Dabih",
  "Dalim",
  "Danfeng",
  "Deneb",
  "Deneb Algedi",
  "Denebola",
  "Diadem",
  "Dilmun",
  "Dingolay",
  "Diphda",
  "Dìwö",
  "Diya",
  "Dofida",
  "Dombay",
  "Dschubba",
  "Dubhe",
  "Dziban",
  "Ebla",
  "Edasich",
  "Electra",
  "Elgafar",
  "Elkurud",
  "Elnath",
  "Eltanin",
  "Emiw",
  "Enif",
  "Errai",
  "Fafnir",
  "Fang",
  "Fawaris",
  "Felis",
  "Felixvarela",
  "Filetdor",
  "Flegetonte",
  "Fomalhaut",
  "Formosa",
  "Franz",
  "Fulu",
  "Fumalsamakah",
  "Funi",
  "Furud",
  "Fuyue",
  "Gacrux",
  "Gakyid",
  "Gar",
  "Garnet Star",
  "Geminga",
  "Giausar",
  "Gienah",
  "Ginan",
  "Gloas",
  "Gnomon",
  "Gomeisa",
  "Graffias",
  "Guahayona",
  "Grumium",
  "Gudja",
  "Gumala",
  "Guniibuu",
  "Hadar",
  "Haedus",
  "Hamal",
  "Hassaleh",
  "Hatysa",
  "Helvetios",
  "Heze",
  "Hoggar",
  "Homam",
  "Horna",
  "Hunahpú",
  "Hunor",
  "Iklil",
  "Illyrian",
  "Imai",
  "Inquill",
  "Intan",
  "Intercrus",
  "Irena",
  "Itonda",
  "Izar",
  "Jabbah",
  "Jishui",
  "Kaffaljidhma",
  "Kaewkosin",
  "Kalausi",
  "Kamuy",
  "Kang",
  "Karaka",
  "Kaus Australis",
  "Kaus Borealis",
  "Kaus Media",
  "Kaveh",
  "Keid",
  "Khambalia",
  "Kitalpha",
  "Kochab",
  "Koeia",
  "Koit",
  "Komondor",
  "Kornephoros",
  "Kosjenka",
  "Kraz",
  "Kuma",
  "Kurhah",
  "La Superba",
  "Larawag",
  "Lerna",
  "Lesath",
  "Libertas",
  "Lich",
  "Liesma",
  "Lilii Borea",
  "Lionrock",
  "Lucilinburhuc",
  "Lusitânia",
  "Maasym",
  "Macondo",
  "Mago",
  "Mahasim",
  "Mahsati",
  "Maia",
  "Malmok",
  "Marfik",
  "Markab",
  "Markeb",
  "Márohu",
  "Marsic",
  "Matar",
  "Matza",
  "Maru",
  "Mazaalai",
  "Mebsuta",
  "Megrez",
  "Meissa",
  "Mekbuda",
  "Meleph",
  "Menkalinan",
  "Menkar",
  "Menkent",
  "Menkib",
  "Merak",
  "Merga",
  "Meridiana",
  "Merope",
  "Mesarthim",
  "Miaplacidus",
  "Mimosa",
  "Minchir",
  "Minelauva",
  "Mintaka",
  "Mira",
  "Mirach",
  "Miram",
  "Mirfak",
  "Mirzam",
  "Misam",
  "Mizar",
  "Moldoveanu",
  "Mönch",
  "Montuno",
  "Morava",
  "Moriah",
  "Mothallah",
  "Mouhoun",
  "Mpingo",
  "Muliphein",
  "Muphrid",
  "Muscida",
  "Musica",
  "Muspelheim",
  "Nahn",
  "Naledi",
  "Naos",
  "Nashira",
  "Násti",
  "Natasha",
  "Navi",
  "Nekkar",
  "Nembus",
  "Nenque",
  "Nervia",
  "Nihal",
  "Nikawiy",
  "Noquisi",
  "Nosaxa",
  "Nunki",
  "Nusakan",
  "Nushagak",
  "Nyamien",
  "Ogma",
  "Okab",
  "Orkaria",
  "Paikauhale",
  "Parumleo",
  "Peacock",
  "Petra",
  "Phact",
  "Phecda",
  "Pherkad",
  "Phoenicia",
  "Piautos",
  "Pincoya",
  "Pipirima",
  "Pipoltr",
  "Pleione",
  "Poerava",
  "Polaris",
  "Polaris Australis",
  "Polis",
  "Pollux",
  "Porrima",
  "Praecipua",
  "Prima Hyadum",
  "Procyon",
  "Propus",
  "Proxima Centauri",
  "Ran",
  "Rana",
  "Rapeto",
  "Rasalas",
  "Rasalgethi",
  "Rasalhague",
  "Rastaban",
  "Regor",
  "Regulus",
  "Revati",
  "Rigel",
  "Rigil Kentaurus",
  "Rosalíadecastro",
  "Rotanev",
  "Ruchbah",
  "Rukbat",
  "Sabik",
  "Saclateni",
  "Sadachbia",
  "Sadalbari",
  "Sadalmelik",
  "Sadalsuud",
  "Sadr",
  "Sagarmatha",
  "Saiph",
  "Salm",
  "Sāmaya",
  "Sansuna",
  "Sargas",
  "Sarin",
  "Sceptrum",
  "Scheat",
  "Schedar",
  "Secunda Hyadum",
  "Segin",
  "Seginus",
  "Sham",
  "Shama",
  "Sharjah",
  "Shaula",
  "Sheliak",
  "Sheratan",
  "Sika",
  "Sirius",
  "Situla",
  "Skat",
  "Solaris",
  "Spica",
  "Sterrennacht",
  "Stribor",
  "Sualocin",
  "Subra",
  "Suhail",
  "Sulafat",
  "Syrma",
  "Tabit",
  "Taika",
  "Taiyangshou",
  "Taiyi",
  "Talitha",
  "Tangra",
  "Tania Australis",
  "Tania Borealis",
  "Tapecue",
  "Tarazed",
  "Tarf",
  "Taygeta",
  "Tegmine",
  "Tejat",
  "Terebellum",
  "Tevel",
  "Thabit",
  "Theemin",
  "Thuban",
  "Tiaki",
  "Tianguan",
  "Tianyi",
  "Timir",
  "Tislit",
  "Titawin",
  "Tojil",
  "Toliman",
  "Tonatiuh",
  "Torcular",
  "Tuiren",
  "Tupã",
  "Tupi",
  "Tureis",
  "Ukdah",
  "Uklun",
  "Unukalhai",
  "Unurgunite",
  "Uruk",
  "Uúba",
  "Vega",
  "Veritate",
  "Vindemiatrix",
  "Wasat",
  "Wattle",
  "Wazn",
  "Wezen",
  "Wouri",
  "Wurren",
  "Xamidimura",
  "Xihe",
  "Xuange",
  "Yed Posterior",
  "Yed Prior",
  "Yildun",
  "Zaniah",
  "Zaurak",
  "Zavijava",
  "Zembra",
  "Zhang",
  "Zibal",
  "Zosma",
  "Zubenelgenubi",
  "Zubenelhakrabi",
  "Zubeneschamali",
].map((x) => x.toLowerCase());
const kPrefixes = [
  "alpha",
  "ancient",
  "beta",
  "chi",
  "delta",
  "epsilon",
  "eta",
  "fast",
  "friendly",
  "gamma",
  "golden",
  "iota",
  "kappa",
  "lambda",
  "mu",
  "nu",
  "omega",
  "omicron",
  "peaceful",
  "phi",
  "pi",
  "psi",
  "rho",
  "sigma",
  "silver",
  "strong",
  "tau",
  "theta",
  "upsilon",
  "watchful",
  "xi",
  "zeta",
].map((x) => x.toLowerCase());
const numerals = [
  "I",
  "II",
  "III",
  "IV",
  "V",
  "VI",
  "VII",
  "VIII",
  "IX",
  "X",
  "XI",
  "XII",
  "XIII",
  "XIV",
];
const romanLetters = ["A", "B", "C", "D", "E"];
const suffixes = ["Prime", "Minor"];

export function randomWord(a: string[]) {
  return a[Math.floor(Math.random() * a.length)];
}
export function randomStarName() {
  const up = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
  const randomUppercased = (a: string[]) => up(randomWord(a));
  const prefix = randomUppercased(kPrefixes);
  const starName = randomUppercased(stars);
  const romanNumeral = randomUppercased(numerals);
  const letter = randomUppercased(romanLetters);
  const suffix = randomUppercased(suffixes);
  const form = Math.random();
  const name =
    form < 0.05
      ? `${starName}`
      : form < 0.6
        ? `${prefix} ${starName}`
        : form < 0.8
          ? `${starName} ${romanNumeral}`
          : form < 0.95
            ? `${starName} ${letter} ${romanNumeral}`
            : `${starName} ${suffix}`;
  return name;
}
